on:
  workflow_dispatch:
  
jobs:
  import_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          npm install @aws-sdk/client-dynamodb @aws-sdk/credential-providers @aws-sdk/shared-ini-file-loader
          npm install yargs

      - name: Run TypeScript script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-2"
        run: |
          for file in data/*.json; do
            table_name=$(basename "$file" .json)
            node import_data_to_dynamodb.js --tableName "$table_name" --sourceFile "$file" --accessKeyId $AWS_ACCESS_KEY_ID --secretAccessKey $AWS_SECRET_ACCESS_KEY --region "us-west-2"
          done
  