name: DynamoDB Data Migration

on:
  workflow_dispatch:
    inputs:
      table_names:
        description: 'Comma-separated table names'
        required: true

jobs:
  export_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set working directory
        run: cd deployments/migrate-tables
        shell: bash

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.SOURCE_AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.SOURCE_AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region "us-west-2"

      - name: Create directory for table data
        run: |
          mkdir -p table_data

      - name: Save table names to file
        run: |
          echo "${{ github.event.inputs.table_names }}" | tr -s ',' '\n' > table_names.txt

      - name: Scan and save table data
        run: |
          while IFS= read -r table_name; do
            echo "Scanning table: $table_name"
            aws dynamodb scan --table-name "$table_name" --region "us-west-2" | jq -r '.Items' > "table_data/${table_name}.json"
            echo "Table data saved: table_data/${table_name}.json"
          done < table_names.txt

      - name: List saved table data
        run: |
          ls -l table_data

      - name: Upload table data as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: DynamoDB Data Migration
          path: ./table_data

  import_data:
    needs: export_data
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set working directory
        run: cd deployments/migrate-tables
        shell: bash

      - name: Download exported data
        uses: actions/download-artifact@v2
        with:
          name: DynamoDB Data Migration
          path: exported_data

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          npm install @aws-sdk/client-dynamodb @aws-sdk/credential-providers @aws-sdk/shared-ini-file-loader
          npm install yargs

      - name: Run TypeScript script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DESTINATION_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DESTINATION_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-2"
        run: |
          for file in exported_data/*.json; do
            table_name=$(basename "$file" .json)
            node import_data_to_dynamodb.js --tableName "$table_name" --sourceFile "$file" --accessKeyId $AWS_ACCESS_KEY_ID --secretAccessKey $AWS_SECRET_ACCESS_KEY --region "us-west-2"
          done