name: DynamoDB Data Migration

on:
  push:
    branches:
      - main

jobs:
  migrate_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region "us-west-2"

      - name: Export data from source DynamoDB table
        run: |
          aws dynamodb scan --table-name "migration-table" --region "us-west-2" > data.json

      - name: Import data into destination DynamoDB table
        run: |
          aws dynamodb batch-write-item --request-items file://data.json --region "us-west-2"
