on:
  push:
    branches:
      - main

jobs:
  migrate_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region "us-west-2"

      - name: Read table names from JSON file
        id: read_table_names
        run: |
          table_names=$(jq -r '.table_names | .[]' table_names.json)
          echo "::set-output name=table_names::$table_names"

      - name: Create directory for table data
        run: |
          mkdir -p table_data

      - name: Scan and save table data
        run: |
          for table_name in "${{ steps.read_table_names.outputs.table_names }}"; do
            echo "Scanning table: $table_name"
            if aws dynamodb scan --table-name "$table_name" --region "us-west-2" > "table_data/${table_name}.json"; then
              echo "Table data saved: table_data/${table_name}.json"
            else
              echo "Error: Failed to scan table $table_name"
            fi
          done

      - name: List saved table data
        run: |
          ls -l table_data

      - name: Upload table data as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: DynamoDB Data Migration
          path: ./table_data
